#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(resolve(__dirname, '../package.json'), 'utf8'));

const out = `// Generated by scripts/gen-version.mjs — do not edit
export const VERSION = '${pkg.version}';
`;

writeFileSync(resolve(__dirname, '../src/version.ts'), out);
console.error(`[gen-version] version.ts written: ${pkg.version}`);
