import { z } from 'zod';
import type { VaultClient } from '../api.js';

// ---------------------------------------------------------------------------
// list_vault_items
// ---------------------------------------------------------------------------

export const listVaultItemsInput = {
  filter: z.string().optional()
    .describe('Case-insensitive substring filter on item names. Omit to return all items.'),
  collection: z.enum(['mcp-exposed', 'mcp-agent-created']).optional()
    .describe('Restrict to one collection. Omit to return items from both mcp-exposed and mcp-agent-created.'),
};

export type ListVaultItemsArgs = {
  filter?: string;
  collection?: 'mcp-exposed' | 'mcp-agent-created';
};

export async function listVaultItems(client: VaultClient, args: ListVaultItemsArgs) {
  return client.listItems(args.filter, args.collection);
}

// ---------------------------------------------------------------------------
// get_vault_metadata
// ---------------------------------------------------------------------------

export const getVaultMetadataInput = {
  name: z.string().min(1)
    .describe('Exact item name (case-sensitive) as it appears in the vault.'),
};

export type GetVaultMetadataArgs = { name: string };

export async function getVaultMetadata(client: VaultClient, args: GetVaultMetadataArgs) {
  return client.getItemDetail(args.name);
}

// ---------------------------------------------------------------------------
// reveal_secret_via_send
// ---------------------------------------------------------------------------

export const revealSecretViaSendInput = {
  name: z.string().min(1)
    .describe('Exact item name (case-sensitive) of the vault item to reveal.'),
  field: z.string().optional()
    .describe(
      'Field to reveal. Defaults to "value" (notes for api-key/password/note items, password for login items). ' +
      'Other options: "username", "password", "totp", "uri0" (or uri1, uri2, ...).',
    ),
  ttl_seconds: z.number().int().min(30).max(86400).optional()
    .describe('Bitwarden Send TTL in seconds. Default 300 (5 min), range [30, 86400].'),
  max_views: z.number().int().min(1).max(100).optional()
    .describe('Maximum number of times the Send URL can be accessed. Default 1, range [1, 100].'),
};

export type RevealSecretViaSendArgs = {
  name: string;
  field?: string;
  ttl_seconds?: number;
  max_views?: number;
};

export async function revealSecretViaSend(client: VaultClient, args: RevealSecretViaSendArgs) {
  return client.revealViaSend(args.name, args.field, args.ttl_seconds, args.max_views);
}

// ---------------------------------------------------------------------------
// get_totp_code
// ---------------------------------------------------------------------------

export const getTotpCodeInput = {
  name: z.string().min(1)
    .describe('Exact item name (case-sensitive) of a vault login item with TOTP configured.'),
};

export type GetTotpCodeArgs = { name: string };

export async function getTotpCode(client: VaultClient, args: GetTotpCodeArgs) {
  const result = await client.getTotpCode(args.name);
  return {
    code: result.code,
    period_seconds: result.period,
    remaining_seconds: result.remainingSeconds,
    algorithm: result.algorithm,
    digits: result.digits,
  };
}

// ---------------------------------------------------------------------------
// save_generated_secret
// ---------------------------------------------------------------------------

export const saveGeneratedSecretInput = {
  name: z.string().min(1).max(200)
    .describe('Unique name for this secret within the mcp-agent-created collection. Case-sensitive. Name collision returns an error — pick a distinct name.'),
  value: z.string().max(4096)
    .describe('The secret value to store (max 4096 chars). Assumed already generated by the agent.'),
  type: z.enum(['password', 'api-key'])
    .describe('Logical type of this secret. "password" for user passwords, "api-key" for API tokens and keys.'),
  notes: z.string().max(2000).optional()
    .describe('Optional non-sensitive annotation (e.g. where this key is used). Not the secret itself.'),
  used_in: z.string().max(500).optional()
    .describe('Free-form context string, e.g. "publish_protected_html @ aiwerk.ch/press/2026-05". Stored as mcp-used-in custom field.'),
  expires_in_days: z.number().int().min(1).max(365).optional()
    .describe('Days until the secret expires (sets mcp-expires-at). Default 30, max 365.'),
};

export type SaveGeneratedSecretArgs = {
  name: string;
  value: string;
  type: 'password' | 'api-key';
  notes?: string;
  used_in?: string;
  expires_in_days?: number;
};

export async function saveGeneratedSecret(client: VaultClient, args: SaveGeneratedSecretArgs) {
  return client.saveGeneratedSecret(args);
}

// ---------------------------------------------------------------------------
// health_check
// ---------------------------------------------------------------------------

export const healthCheckInput = {};

export type HealthCheckArgs = Record<string, never>;

export async function healthCheck(client: VaultClient, _args: HealthCheckArgs) {
  return client.healthCheck();
}
